In [1]:
from statsmodels.formula.api import ols
import pandas as pd
import numpy as np

# Setup

In this problem, you will look at a data set tracking properties sold in NYC over a 12-month period. This may be of interest to potential sellers and real estate agents deciding how to price new sales. Some of the relevant columns in this data set are as follows:

* RESIDENTIAL_UNITS, COMMERCIAL_UNITS, TOTAL_UNITS
* LAND_SQUARE_FEET, GROSS_SQUARE_FEET
* YEAR_BUILT
* SALE_PRICE

We will treat Sale Price as the outcome variable and some of the other columns as predictors. The CSV file contains missing data, so we will clean it up by replacing those instances with `nan`s, which `ols` will then drop from consideration.

In [2]:
Sales = pd.read_csv("NYC_Sales_Samples.csv")
Sales = Sales.replace("-",np.nan)\
    .astype({"LAND_SQUARE_FEET":"float", "GROSS_SQUARE_FEET":"float", "YEAR_BUILT":"float"})
Sales.head()

BOROUGH        NEIGHBORHOOD  RESIDENTIAL_UNITS  COMMERCIAL_UNITS  \
0        3  DOWNTOWN-METROTECH                  0                 2   
1        3  DOWNTOWN-METROTECH                  0                 2   
2        4     JACKSON HEIGHTS                198                 0   
3        1        MIDTOWN WEST                  8                 3   
4        3         FORT GREENE                  0                 3   

   TOTAL_UNITS  LAND_SQUARE_FEET  GROSS_SQUARE_FEET  YEAR_BUILT   SALE_PRICE  
0            2           20704.0           206000.0      1967.0  138000000.0  
1            2           20600.0           164115.0      1926.0   98463962.0  
2          198           59000.0           194450.0      1940.0   85091472.0  
3           11            2008.0             8950.0      1920.0   83000000.0  
4            3           12415.0            36000.0      1920.0   68000000.0

# Part 1 [6 pts]

* Regress SALE_PRICE on all columns except for BOROUGH and NEIGHBORHOOD, and show the summary table.

* Briefly explain what we can infer about the three UNITS coefficients from their standard errors and $p$-values.

* Check the estimator covariance matrix using `.cov_params()`. What does this tell you about the three UNITS predictors? How do your observations relate to the standard errors observed above?

In [3]:
model = ols("SALE_PRICE ~ RESIDENTIAL_UNITS+COMMERCIAL_UNITS+TOTAL_UNITS+LAND_SQUARE_FEET+GROSS_SQUARE_FEET+YEAR_BUILT", Sales).fit()
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:             SALE_PRICE   R-squared:                       0.643
Model:                            OLS   Adj. R-squared:                  0.641
Method:                 Least Squares   F-statistic:                     436.9
Date:                Mon, 23 Sep 2024   Prob (F-statistic):          2.94e-321
Time:                        02:08:19   Log-Likelihood:                -24228.
No. Observations:                1463   AIC:                         4.847e+04
Df Residuals:                    1456   BIC:                         4.851e+04
Df Model:                           6                                         
Covariance Type:            nonrobust                                         
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept          1.064e+07   6.22e+06      1.711      0.087   -1.56e+06    2.28e+07
RESIDENTIAL_UNITS  6.058e+04   3.78e+06      0.016      0.987   -7.36e+06    7.48e+06
COMMERCIAL_UNITS   4.564e+05   3.78e+06      0.121      0.904   -6.95e+06    7.87e+06
TOTAL_UNITS       -2559.8198   3.78e+06     -0.001      0.999   -7.42e+06    7.41e+06
LAND_SQUARE_FEET   -130.4779      8.360    -15.607      0.000    -146.878    -114.078
GROSS_SQUARE_FEET   479.4103     12.446     38.520      0.000     454.997     503.824
YEAR_BUILT        -5419.6597   3201.255     -1.693      0.091   -1.17e+04     859.905
==============================================================================
Omnibus:                     1739.187   Durbin-Watson:                   1.295
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          2691575.505
Skew:                           5.065   Prob(JB):                         0.00
Kurtosis:                     212.885   Cond. No.                     1.04e+06
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.04e+06. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [4]:
es_cov = model.cov_params()
es_cov

Intercept  RESIDENTIAL_UNITS  COMMERCIAL_UNITS  \
Intercept          3.865444e+13       5.922712e+11      5.483410e+11   
RESIDENTIAL_UNITS  5.922712e+11       1.429827e+13      1.427213e+13   
COMMERCIAL_UNITS   5.483410e+11       1.427213e+13      1.427419e+13   
TOTAL_UNITS       -5.991510e+11      -1.429807e+13     -1.427204e+13   
LAND_SQUARE_FEET   1.610496e+06       3.923127e+04      6.759491e+04   
GROSS_SQUARE_FEET  4.932353e+06       5.645356e+05      1.506333e+05   
YEAR_BUILT        -1.990003e+10      -3.094810e+08     -2.880316e+08   

                    TOTAL_UNITS  LAND_SQUARE_FEET  GROSS_SQUARE_FEET  \
Intercept         -5.991510e+11      1.610496e+06       4.932353e+06   
RESIDENTIAL_UNITS -1.429807e+13      3.923127e+04       5.645356e+05   
COMMERCIAL_UNITS  -1.427204e+13      6.759491e+04       1.506333e+05   
TOTAL_UNITS        1.429820e+13     -9.821683e+03      -6.895942e+05   
LAND_SQUARE_FEET  -9.821683e+03      6.989607e+01      -4.729162e+01   
GROSS_SQUARE_FEET -6.895942e+05     -4.729162e+01       1.548966e+02   
YEAR_BUILT         3.127789e+08     -9.185072e+02      -2.531605e+03   

                     YEAR_BUILT  
Intercept         -1.990003e+10  
RESIDENTIAL_UNITS -3.094810e+08  
COMMERCIAL_UNITS  -2.880316e+08  
TOTAL_UNITS        3.127789e+08  
LAND_SQUARE_FEET  -9.185072e+02  
GROSS_SQUARE_FEET -2.531605e+03  
YEAR_BUILT         1.024804e+07

 # Analyze for question 2 and 3 
 2. As we can see, att UNITS coeficients have relatively large std err and p value (much greater than 0.05). The large std err indicates a large uncertainty, and the large p value indicates that we can't reject null hypothesis. Combing these two we can tell that the UNUIT coefficients are not good predictors in this case, as they're not providing very meaningful information.
 3. We can see we get a large number for the diagonal of the covariance matrix for the UNIT coefficients. This means that thses coefficients has large uncertainty. What we got for part 3 correspond with what we got for question 2. 

# Part 2 [6 pts]

* Now estimate a new model and show the summary, this time dropping RESIDENTIAL_UNITS, COMMERCIAL_UNITS and LAND_SQUARE_FEET. There should be three predictors.

* Again, briefly explain what we can infer about the coefficients from their standard errors and $p$-values.

* Compare the $R^2$ values of this model with the one from Part 1. Based solely on this value, which model has a better fit? Why might we prefer a model with a lower $R^2$ value?

In [8]:
model2 = ols("SALE_PRICE ~ TOTAL_UNITS+GROSS_SQUARE_FEET+YEAR_BUILT", Sales).fit()
model2.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:             SALE_PRICE   R-squared:                       0.580
Model:                            OLS   Adj. R-squared:                  0.579
Method:                 Least Squares   F-statistic:                     672.0
Date:                Mon, 23 Sep 2024   Prob (F-statistic):          2.21e-274
Time:                        02:17:09   Log-Likelihood:                -24363.
No. Observations:                1464   AIC:                         4.873e+04
Df Residuals:                    1460   BIC:                         4.876e+04
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept          1.522e+07   6.71e+06      2.268      0.023    2.06e+06    2.84e+07
TOTAL_UNITS        1.132e+05   1.93e+04      5.858      0.000    7.53e+04    1.51e+05
GROSS_SQUARE_FEET   396.6846     11.729     33.820      0.000     373.677     419.693
YEAR_BUILT        -7927.2757   3455.323     -2.294      0.022   -1.47e+04   -1149.348
==============================================================================
Omnibus:                     1803.270   Durbin-Watson:                   1.242
Prob(Omnibus):                  0.000   Jarque-Bera (JB):          2001017.688
Skew:                           5.558   Prob(JB):                         0.00
Kurtosis:                     183.776   Cond. No.                     7.20e+05
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 7.2e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [10]:
r_sqr2 = model2.rsquared
r_sqr2

0.5799924259745989

In [11]:
r_sqr = model.rsquared
r_sqr

0.6429042391249843

# Analysis for question 2 and 3
1. This time with this setting, we can see the three variables all reject null hypothesis. The std err of TOTAL_UNITS also gets lower than the previous case, smaller than coefficient, meaning the new model is more reasonable than the previous one.
2. We can see the second moddel with a lower r squred value. Solely from the value, model 1 best fit better, but we migt prefer model with lower r suqred value as we want to avoid possible overfitting, or like this case though model 2 with lower r squired value, the stad err and p value of it indicates we might prefer model 2 here. 

# Part 3 [6 pts]

* Create arrays for the matrix $X$ and vector $\mathbf y$ from Part 2. Drop all rows containing `nan` values, and don't forget to add the column of 1s to $X$.

* Use the OLS solution formula to compute and show $\hat\beta$ (these should be identical to the results in Part 2). Then use these to compute the predictions $\mathbf{\hat y}$ and the sum of squared residuals. You may find `numpy.linalg.inv()` useful. 

* Compute and show the sample estimate of the error variance $\hat{\sigma}^2$ and the sample estimate of the estimator covariance matrix $\hat{Var}(\hat\beta)$.  

In [30]:
dropNa = Sales[["TOTAL_UNITS", "GROSS_SQUARE_FEET", "YEAR_BUILT", "SALE_PRICE"]].dropna()
X = dropNa[["TOTAL_UNITS", "GROSS_SQUARE_FEET", "YEAR_BUILT"]].values
y = dropNa["SALE_PRICE"].values
X = np.hstack((X,np.ones([X.shape[0],1], X.dtype)))
X

array([[2.00000e+00, 2.06000e+05, 1.96700e+03, 1.00000e+00],
       [2.00000e+00, 1.64115e+05, 1.92600e+03, 1.00000e+00],
       [1.98000e+02, 1.94450e+05, 1.94000e+03, 1.00000e+00],
       ...,
       [1.00000e+00, 1.83600e+03, 1.92500e+03, 1.00000e+00],
       [4.00000e+00, 3.30000e+03, 1.93100e+03, 1.00000e+00],
       [5.00000e+00, 2.00000e+03, 1.93100e+03, 1.00000e+00]])

In [31]:
y

array([1.3800000e+08, 9.8463962e+07, 8.5091472e+07, ..., 1.0000000e+05,
       1.0000000e+05, 1.0000000e+05])

In [32]:
X.shape

(1464, 4)

In [33]:
y.shape

(1464,)

In [40]:
# According to the lecture notes, we have the solution to OLS is:
beta_hat = np.linalg.inv(X.T @ X) @ X.T @ y
y_hat = X @ beta_hat
res = y - y_hat # ****** res_i = y_i - y_hat_i
RSS = np.sum(res ** 2)
print(beta_hat)
print(y_hat)
print(RSS)

[ 1.13193547e+05  3.96684619e+02 -7.92727573e+03  1.52215971e+07]
[81572064.28435203 65281947.34200311 99390328.65107743 ...
   803097.85910404  1675861.12807449  1273364.67125381]
2.441461418686264e+16


In [44]:
# Based on the lecture notes we have:
n = X.shape[0]
k = X.shape[1]
var = RSS / (n - k - 1)
var

16733799990995.64

In [45]:
var_b = var * np.linalg.inv(X.T @ X)
var_b

array([[ 3.73639555e+08, -1.25623507e+05,  4.28802876e+06,
        -8.81070537e+09],
       [-1.25623507e+05,  1.37669905e+02, -3.40248768e+03,
         6.45273661e+06],
       [ 4.28802876e+06, -3.40248768e+03,  1.19474416e+07,
        -2.32009168e+10],
       [-8.81070537e+09,  6.45273661e+06, -2.32009168e+10,
         4.50673208e+13]])